Qartuli = int(input("Score "))
English = int(input("Score "))
german = int(input("Score "))
Sport = int(input("Score "))
it = int(input("Score "))
Music = int(input("Score "))
History = int(input("Score "))
math = int(input("Score "))
print(Qartuli + English + german + Sport + it + Music + History + math / 5)